#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-libcst
Version  : 0.3.23
Release  : 12
URL      : https://files.pythonhosted.org/packages/9a/b7/20e61cebfb1ddc1b145c3f24361cd3fd5fb3310c2ba667e05cd4b4871d36/libcst-0.3.23.tar.gz
Source0  : https://files.pythonhosted.org/packages/9a/b7/20e61cebfb1ddc1b145c3f24361cd3fd5fb3310c2ba667e05cd4b4871d36/libcst-0.3.23.tar.gz
Summary  : A concrete syntax tree with AST-like properties for Python 3.5, 3.6, 3.7 and 3.8 programs.
Group    : Development/Tools
License  : MIT
Requires: pypi-libcst-python = %{version}-%{release}
Requires: pypi-libcst-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: libcst
Provides: libcst-python
Provides: libcst-python3
BuildRequires : pypi(dataclasses)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(typing_extensions)
BuildRequires : pypi(typing_inspect)

%description
.. image:: docs/source/_static/logo/horizontal.svg
:width: 600 px
:alt: LibCST
A Concrete Syntax Tree (CST) parser and serializer library for Python

%package python
Summary: python components for the pypi-libcst package.
Group: Default
Requires: pypi-libcst-python3 = %{version}-%{release}

%description python
python components for the pypi-libcst package.


%package python3
Summary: python3 components for the pypi-libcst package.
Group: Default
Requires: python3-core
Provides: pypi(libcst)
Requires: pypi(dataclasses)
Requires: pypi(pyyaml)
Requires: pypi(typing_extensions)
Requires: pypi(typing_inspect)

%description python3
python3 components for the pypi-libcst package.


%prep
%setup -q -n libcst-0.3.23
cd %{_builddir}/libcst-0.3.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641453418
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
